### PR TITLE
fix: allow async client shutdowns for multithreading safety.

### LINKED ISSUE #135: Segfault due to race conditions in discord_cleanup when called from another thread
## Describe the bug
I'm using `libdiscord` in a shared library module that I built for a large multithreaded application, e.g. Concord is only a very small part of the entire program, and there are lots of other threads. Everything is pretty much working, but I'm having segmentation faults on shut down, and it appears it may be because I'm shutting down the client in one thread, and perhaps this isn't legal. I looked at some of the code and it appears if `have_sigint` is set, then `discord_run` will exit. I'm not using SIGINT because that only makes sense for a standalone program, but perhaps this suggests that there's no way to terminate a session "out of band" (apart from this mechanism)? Is this the right understanding?

Essentially, I have this (some stuff removed for conciseness):

```
static void *discord_relay(void *varg)
{
	struct discord *client = varg;
	discord_run(client);
	return NULL;
}

static int load_module(void)
{
	ccord_global_init();
    discord_client = discord_init(token);
	if (!discord_client) {
		return -1;
	}

    discord_add_intents(discord_client, DISCORD_GATEWAY_MESSAGE_CONTENT | DISCORD_GATEWAY_GUILD_MESSAGES | DISCORD_GATEWAY_GUILD_MEMBERS);

    discord_set_on_ready(discord_client, &on_ready);
    discord_set_on_message_create(discord_client, &on_message_create);
    discord_set_on_message_update(discord_client, &on_message_update);
	discord_set_on_guild_members_chunk(discord_client, &on_guild_members_chunk);

	if (pthread_create(&discord_thread, NULL, discord_relay, discord_client)) {
		discord_shutdown(discord_client);
		discord_cleanup(discord_client);
		ccord_global_cleanup();
		return -1;
	}
	return 0;
}

static int unload_module(void)
{
	discord_shutdown(discord_client);
	pthread_join(discord_thread, NULL);
	discord_cleanup(discord_client);

    ccord_global_cleanup();
	return 0;
}
```

I initially had this ordering:
```
discord_shutdown(discord_client);
discord_cleanup(discord_client);
pthread_join(discord_thread, NULL);
```

When I did this, I got segmentation faults in the thread with `discord_run`, suggesting that perhaps it is *not* legal to call `discord_shutdown` in another thread. However, I need to be able to do that... how else can I tell the client to exit?

With the ordering shown in the larger snippet, `pthread_join` never returns, so the unload blocks forever (though no crash).

Is there an example or suggested approaching for doing an out of band shutdown as I'm trying to do here? I'd think this would be a common use case, but I didn't find any examples of it. It seems like there is a race condition here with the way I'm currently doing it that leads to the `discord_run` thread trying to read invalid memory... and if I don't call `discord_shutdown`, then the `discord_run` thread won't exit, so I'm not sure if there's a way around that.

Perhaps something like the following could be added to `src/concord-once.c`? (Although I'm not positive if this would be the right fix or not.)

```
static void ccord_shutdown_notify(int signum)
{
    ccord_has_sigint = 1;
}
```

My thinking is this would allow the discord_thread to gracefully exit on its own, and then I could call `pthread_join` directly, since the `discord_run` thread itself appears to call `discord_shutdown` on its own. So really, maybe what's need is just a way to asynchronously shut down using a public function, generically, not just the internal SIGINT handler which doesn't apply to every use case. (Correct me if I'm wrong, but I don't think this currently exists from what I could find.)

This happens consistently if I shut down my program (which unloads all dynamic modules), but not always (only sometimes) if I only attempt to unload the Discord module:

## Stack Trace for full shutdown
```

==534690== 1 errors in context 16 of 29:
==534690== Invalid read of size 8
==534690==    at 0x4F273D3: ??? (in /usr/lib/x86_64-linux-gnu/libcurl.so.4.7.0)
==534690==    by 0x4EF747F: ??? (in /usr/lib/x86_64-linux-gnu/libcurl.so.4.7.0)
==534690==    by 0x4F0A32F: ??? (in /usr/lib/x86_64-linux-gnu/libcurl.so.4.7.0)
==534690==    by 0x4F286AF: ??? (in /usr/lib/x86_64-linux-gnu/libcurl.so.4.7.0)
==534690==    by 0x4F298D6: ??? (in /usr/lib/x86_64-linux-gnu/libcurl.so.4.7.0)
==534690==    by 0x4F2A225: curl_multi_perform (in /usr/lib/x86_64-linux-gnu/libcurl.so.4.7.0)
==534690==    by 0x4F2A562: ??? (in /usr/lib/x86_64-linux-gnu/libcurl.so.4.7.0)
==534690==    by 0x4F2A679: curl_multi_socket_all (in /usr/lib/x86_64-linux-gnu/libcurl.so.4.7.0)
==534690==    by 0x9253F2C: ws_multi_socket_run (in /usr/local/lib/libdiscord.so)
==534690==    by 0x91CAA39: discord_gateway_perform (in /usr/local/lib/libdiscord.so)
==534690==    by 0x91C9EFF: _discord_on_gateway_perform (in /usr/local/lib/libdiscord.so)
==534690==    by 0x924E86F: io_poller_perform (in /usr/local/lib/libdiscord.so)
==534690==  Address 0xb485e50 is 192 bytes inside a block of size 6,440 free'd
==534690==    at 0x48399AB: free (vg_replace_malloc.c:538)
==534690==    by 0x4F0A89A: ??? (in /usr/lib/x86_64-linux-gnu/libcurl.so.4.7.0)
==534690==    by 0x4F00B78: curl_easy_cleanup (in /usr/lib/x86_64-linux-gnu/libcurl.so.4.7.0)
==534690==    by 0x92550AE: _cws_cleanup (in /usr/local/lib/libdiscord.so)
==534690==    by 0x9256F10: cws_free (in /usr/local/lib/libdiscord.so)
==534690==    by 0x9253325: ws_cleanup (in /usr/local/lib/libdiscord.so)
==534690==    by 0x91CA291: discord_gateway_cleanup (in /usr/local/lib/libdiscord.so)
==534690==    by 0x91C56FB: discord_cleanup (in /usr/local/lib/libdiscord.so)
==534690==    by 0x9183699: unload_module (mod_discord.c:409)
```

## Stack Trace for explicit unload
```
==534944== 2 errors in context 17 of 34:
==534944== Invalid read of size 4
==534944==    at 0x4FE09F9: pthread_mutex_trylock (pthread_mutex_trylock.c:42)
==534944==    by 0xFB6EEBB: discord_requestor_dispatch_responses (in /usr/local/lib/libdiscord.so)
==534944==    by 0xFB761AB: discord_run (in /usr/local/lib/libdiscord.so)
==534944==    by 0x9183207: discord_relay (mod_discord.c:322)
==534944==    by 0x134D81: thread_run (thread.c:252)
==534944==    by 0x4FDDEA6: start_thread (pthread_create.c:477)
==534944==    by 0x50F4A2E: clone (clone.S:95)
==534944==  Address 0xfac8be0 is 96 bytes inside a block of size 120 free'd
==534944==    at 0x48399AB: free (vg_replace_malloc.c:538)
==534944==    by 0xFB6E213: discord_requestor_cleanup (in /usr/local/lib/libdiscord.so)
==534944==    by 0xFB6D93F: discord_rest_cleanup (in /usr/local/lib/libdiscord.so)
==534944==    by 0xFB736E9: discord_cleanup (in /usr/local/lib/libdiscord.so)
==534944==    by 0x9183699: unload_module (mod_discord.c:409)
```

### PR DESCRIPTION
**Pull request by InterLinked1**
Currently, if users attempt to compel concord to exit, e.g. using discord_shutdown, this will result in thread unsafe operations that can lead to a segfault.

This allows users to safely cause concord to exit, leveraging the existing flag used for SIGINT handling.

Fixes #135

## Notice
- [X ] I *understand* the code that I have edited, and have the means
to test it before making changes to Concord.

## What?

This allows for multithread safe shutdowns, using the same functionality that the SIGINT handler uses.

## Why?
Prevents segfaults on shutdown.

## How?
Uses the same functionality as SIGINT handler.

## Testing?
Tested locally and successfully prevents segfaults. Users can call pthread_join on any client threads and they will exit momentarily on their own, cleanly.

### CODE REVIEW

**Review by HackerSmacker — APPROVED** [review]
Simple and effective. I'm putting in my yay-for-approval here.

File: src/concord-once.c [hunk 1]
```diff
@@ -9,6 +9,12 @@ int ccord_has_sigint = 0;
 
 static int once;
 
+void
+ccord_shutdown_async(void)
+{
+    ccord_has_sigint = 1;
```
Comment (lcsmuller) [inline src/concord-once.c:15]: Nit: because this function may be called from separate threads we should probably enclose the global var with mutexes, we can initialize a global lock for it like so:
```c
static pthread_mutex_t g_lock = PTHREAD_MUTEX_INITIALIZER;
```
And then use it like so:
```suggestion
    pthread_mutex_lock(&g_lock);
    ccord_should_shutdown = 1; // makes sense to rename this too
    pthread_mutex_unlock(&g_lock);
```
Thoughts?

Comment (InterLinked1) [reply src/concord-once.c:15]: I guess that makes sense, although I'm not following how calling ccord_shutdown_async might be multithread unsafe on its own. Once the flag is set to 1, then any other calls to the function are basically a no op, right? i.e. it can only go from 0 to 1, or am I wrong about that?

Comment (lcsmuller) [reply src/concord-once.c:15]: The flag is being checked at `discord_run()` so there should be a very slim (although not impossible) chance that it will read at the same time as `ccord_shutdown_async()` is writing to it.

See [here](https://github.com/Cogmasters/concord/blob/38dc9b2ea40cf4c87d81f7dd92639987fc8e946a/src/discord-loop.c#L114), we would also need to add locking here

But in all honesty, this is just me being pedantic

Comment (HackerSmacker) [reply src/concord-once.c:15]: I think this is good, but, I will say this, in the context of a complex program with many running threads all doing something:

From the library standpoint, it's going out and is going to be shut down, so, you might as well just terminate it; locking it truly wouldn't make a big difference.

From the program standpoint, it somewhat makes sense to lock the shutdown flag -- you might want to reactivate Concord without a total restart!

Comment (InterLinked1) [reply src/concord-once.c:15]: Ah, I was anticipating ccord_shutdown_async would only be used on shutdowns. If not, then maybe some locking is needed. (In the case of a shutdown, I don't think it matters if there's a simultaneous read: `discord_read` might read 0 on one iteration, but eventually it's guaranteed to read 1, just perhaps on the next loop instead of the current one, so there's no wrong behavior if it's an inconsistent read.)

If we need to lock in discord-loop, a static lock won't work; should this be non-static and simply referenced extern in discord-loop.c, just like ccord_has_sigint?

If we're renaming things anyways, then maybe `shutdown_lock` is a more descriptive name than `g_lock`?

Comment (lcsmuller) [reply src/concord-once.c:15]: > If we need to lock in discord-loop, a static lock won't work; should this be non-static and simply referenced extern in discord-loop.c, just like ccord_has_sigint?

Yup, or perhaps we wrap `ccord_has_sigint` in a function and then there's no need to be extern'ing variables? Ex
```c
int
discord_will_shutdown(void) {
  int retval;
  pthread_mutex_lock(&shutdown_lock);
  retval = ccord_will_shutdown;
  pthread_mutex_unlock(&shutdown_unlock);
  return retval;
}
```

> If we're renaming things anyways, then maybe shutdown_lock is a more descriptive name than g_lock?

Sure, I'm fine with it!

Comment (InterLinked1) [reply src/concord-once.c]: Okay, I added another commit to the PR that hopefully addresses all these comments.

**Review by lcsmuller — APPROVED** [review]
Looks good, feel free to join our Discord server to participate in our contributor-exclusive channels!

**Comment by InterLinked1** [comment]
> Looks good, feel free to join our Discord server to participate in our contributor-exclusive channels!

Thanks for moving quickly on this, nice having this fixed!
I'm not actually much of a Discord person myself, but some of my users are, so I've been working on a Discord/IRC relay module using libdiscord (concord): https://github.com/InterLinked1/lbbs/blob/master/modules/mod_discord.c

Still a couple things to work out, but it's working pretty well!

**Comment by HackerSmacker** [comment]
Hey, that's brilliant! I think this will make a nice replacement to an existing (and memory-eating) Javascript-based relay bot we've got!
